version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: shiny
    image: naturecons/wheretowork:latest
    ports:
      - "127.0.0.1:3939:3838"
    environment:
      # environmental variables defined in ./.env
      - FORCE_DEFAULT_PROJECTS
      - PROJECT_DIRECTORY
      - R_CONFIG_ACTIVE
    volumes:
      - "${PROJECT_DIRECTORY}:/projects"
